#
# DemoGame
# demogame - 2019

dist: xenial

services:
- docker
- xvfb

language: java
jdk:
  - openjdk8
  - openjdk11

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

#sudo: false
script: mvn clean test install

# Improve build speed
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.cache"

#before_install:
#  - chmod +x mvn

# Define X11 env. for test execution
before_script:
  - "export AUDIODEV=null"
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
#  - sleep 3 # give xvfb some time to start

# Deploy operation
deploy:
  provider: script
  script: "cp .m2/travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    tags: true

